### ISSUE TITLE
'Sample Data' folder

### ISSUE THREAD

**Issue by bloodraven66** [bloodraven66/tonicBurstingPackage#4]
Hi,
I see you have added 'Sample Data' folder, is this intentional?
If so, can we have the data some place else instead of github? (eg: in dropbox as a zip file, can be automatically downloaded in python)

**Comment by varmaalok22** [comment]
Alternatively, we could have a function that loads some sample data, with options for which dataset to load. What would you recommend is the best way to do this? Should the function explicitly store the matrices of the data, or should we put it in Dropbox, as you were suggesting? Are there some good alternatives to Dropbox? My drive is full and I don't really like Dropbox so much, so I've not done anything about it.

**Comment by bloodraven66** [comment]
> 

Yes I think we can have a function to load sample dataset (s). 

Actually, we can store the data in huggingface itself (where the models are uploaded) (https://huggingface.co/docs/datasets/upload_dataset#:~:text=Upload%20dataset,lines%2C%20text%2C%20and%20Parquet.)
You can create a repository in huggingface and upload zip files of dataset as I have done for models - https://huggingface.co/viks66/TVB/tree/main, or you can share the data with me and I can add with my account.

the dataset will downloaded with huggingface api when be the function is called

**Comment by bloodraven66** [comment]
Also, it is a good idea to fill in model card in hugging face for the pretrained models - https://huggingface.co/viks66/TVB/blob/main/README.md

Can you add some details for the task - what is the dataset used, how is the dataset obtained, (refs if any), where will the model be used etc. You can open a pull request with your account to modify the file
I'll add info specify to each of the model architectures

**Comment by varmaalok22** [comment]
Ok. I've made an account on Huggingface. I'll edit the README a bit to give the necessary details. I'll also upload some sample data there, and give you info about what each dataset is, so that the load_sample_dataset function can be written. The documentation says that only CSV, JSON, text and Parquet files are accepted. The data I have are all .mat files, and in the future also, it's likely that data will either be in pickle or mat format.

**Comment by bloodraven66** [comment]
> Ok. I've made an account on Huggingface. I'll edit the README a bit to give the necessary details. I'll also upload some sample data there, and give you info about what each dataset is, so that the load_sample_dataset function can be written. The documentation says that only CSV, JSON, text and Parquet files are accepted. The data I have are all .mat files, and in the future also, it's likely that data will either be in pickle or mat format.

I just tried, I was able to upload a zip file, any format should work I think.
You can go to new dataset -> files and versions -> add file

**Comment by varmaalok22** [comment]
Ok. Super - I'll upload it shortly and let you know.

**Comment by varmaalok22** [comment]
Uploaded the data. There are 3 sets of data in the uploaded .zip file:

Set 1 and Set 2 have reconstructions from artificially generated spike trains. Both of these are from different runs of the simulation, and have switches in state.
Set 3 is the ground truth calcium imaging data from Purkinje neurons obtained using GCaMP5G and widefield imaging. dF/F values were calculated and the traces have already been interpolated to a sampling rate of 30Hz and a Gaussian filtered to denoise them.

All datafiles are .mat files and have the following variables:
'ss', 'cf', 'time', 'calcium', 'state' and 'cell_id' (the last one is only in Set 3). As the variable names suggest, 'ss' and 'cf' have time stamps of simple spikes and CF inputs; 'time' has the timestamps, 'calcium' has the dF/F signal, from either the experiment or the generative model; 'state' has the same dimensions as 'time' and stores the state of the cell at each timepoint - 0 is 'Bursting' and 1 is 'Tonic'.

**Comment by bloodraven66** [comment]
Ok, can you share the link to the repository, I can work on the codes tomorrow.

Also, should we have any filtering method in the package?

**Comment by bloodraven66** [comment]
> can you share the link to the repository,

nvm, I see the pull request

**Comment by varmaalok22** [comment]
Super. I've removed the "Sample Data" folder from the GitHub repository now. Closing this thread.
